---

# model hyperparameters
embedding_dim: 16
gnn_hidden_dim: 64
gnn_out_dim: 16
fc1_out_dim: 16

# training parameters
batch_size_train: 256
batch_size_val: 256
batch_size_test: 256
num_epochs: 50
patience: 10
min_delta: 0.00001
lr: 0.01